[2025-06-12 01:51:34,306] [INFO] app: App startup
[2025-06-12 01:51:34,736] [INFO] app: App startup
[2025-06-12 01:51:38,420] [INFO] app.middleware: Request 783a1d6b-fa01-4bcf-885a-bd6a7b10bd23: POST /api/auth/login
[2025-06-12 01:51:38,434] [ERROR] app.blueprints.auth: Login error: False
[2025-06-12 01:51:38,434] [INFO] app.middleware: Response 783a1d6b-fa01-4bcf-885a-bd6a7b10bd23: 500 (0.015s)
[2025-06-12 01:54:02,017] [INFO] app: App startup
[2025-06-12 01:55:51,452] [INFO] app: App startup
[2025-06-12 01:55:54,934] [INFO] app.middleware: Request b433adac-995f-451a-8169-3e448a666c91: POST /api/auth/login
[2025-06-12 01:55:54,949] [ERROR] app.blueprints.auth: Login error: False
[2025-06-12 01:55:54,950] [ERROR] app.blueprints.auth: Login error: {e}
Traceback (most recent call last):
  File "D:\Dynamic Workflow\workflow-management-system\backend\app\blueprints\auth.py", line 89, in login
    data = sanitize_input(request.get_json())
                          ^^^^^^^^^^^^^^^^^^
  File "D:\Dynamic Workflow\workflow-management-system\backend\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 599, in get_json
    if cache and self._cached_json[silent] is not Ellipsis:
                 ~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: False
[2025-06-12 01:55:54,975] [INFO] app.middleware: Response b433adac-995f-451a-8169-3e448a666c91: 500 (0.041s)
[2025-06-12 01:57:35,327] [INFO] app: App startup
[2025-06-12 01:57:35,585] [INFO] app: App startup
[2025-06-12 02:00:09,648] [INFO] app.middleware: Request 50dbc76c-598e-427c-a08d-5c07061b9655: POST /api/auth/login
[2025-06-12 02:00:09,665] [ERROR] app.blueprints.auth: Login error: False
[2025-06-12 02:00:09,665] [ERROR] app.blueprints.auth: Login error: {e}
Traceback (most recent call last):
  File "D:\Dynamic Workflow\workflow-management-system\backend\app\blueprints\auth.py", line 89, in login
    data = sanitize_input(request.get_json())
                          ^^^^^^^^^^^^^^^^^^
  File "D:\Dynamic Workflow\workflow-management-system\backend\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 599, in get_json
    if cache and self._cached_json[silent] is not Ellipsis:
                 ~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: False
[2025-06-12 02:00:09,665] [INFO] app.middleware: Response 50dbc76c-598e-427c-a08d-5c07061b9655: 500 (0.016s)
[2025-06-12 02:01:29,714] [INFO] app.middleware: Request 47832b81-11f4-4960-9516-eb1f072255ca: POST /api/auth/login
[2025-06-12 02:01:29,714] [ERROR] app.blueprints.auth: Login error: False
[2025-06-12 02:01:29,714] [ERROR] app.blueprints.auth: Login error: {e}
Traceback (most recent call last):
  File "D:\Dynamic Workflow\workflow-management-system\backend\app\blueprints\auth.py", line 89, in login
    data = sanitize_input(request.get_json())
                          ^^^^^^^^^^^^^^^^^^
  File "D:\Dynamic Workflow\workflow-management-system\backend\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 599, in get_json
    if cache and self._cached_json[silent] is not Ellipsis:
                 ~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: False
[2025-06-12 02:01:29,714] [INFO] app.middleware: Response 47832b81-11f4-4960-9516-eb1f072255ca: 500 (0.000s)
[2025-06-12 02:06:49,028] [INFO] app: App startup
[2025-06-12 02:07:33,792] [INFO] app: App startup
[2025-06-12 02:07:39,812] [INFO] app: App startup
[2025-06-12 02:07:40,080] [INFO] app: App startup
[2025-06-12 02:07:43,699] [INFO] app.middleware: Request 67b96d69-20f5-462b-989c-06a8abe452ef: POST /api/auth/login
[2025-06-12 02:07:43,786] [INFO] app.database: <connection object at 0x0000022F16CF4150; dsn: 'user=postgres password=xxx dbname=workflow_db host=localhost port=5432', closed: 0>
[2025-06-12 02:07:43,967] [INFO] app.middleware: Response 67b96d69-20f5-462b-989c-06a8abe452ef: 401 (0.269s)
[2025-06-12 02:08:34,488] [INFO] app.middleware: Request b2a291ca-c88e-48d2-864a-fef823693952: POST /api/auth/login
[2025-06-12 02:08:34,522] [INFO] app.database: <connection object at 0x0000022F16CF7780; dsn: 'user=postgres password=xxx dbname=workflow_db host=localhost port=5432', closed: 0>
[2025-06-12 02:08:34,703] [INFO] app.middleware: Response b2a291ca-c88e-48d2-864a-fef823693952: 401 (0.215s)
[2025-06-12 02:09:03,933] [INFO] app.middleware: Request c922302a-344d-4061-b1aa-3701b05bbf0f: POST /api/auth/login
[2025-06-12 02:09:03,978] [INFO] app.database: <connection object at 0x0000022F16CF7780; dsn: 'user=postgres password=xxx dbname=workflow_db host=localhost port=5432', closed: 0>
[2025-06-12 02:09:04,233] [INFO] app.middleware: Response c922302a-344d-4061-b1aa-3701b05bbf0f: 401 (0.299s)
[2025-06-12 02:09:15,661] [INFO] app.middleware: Request cf54012b-bf82-4f40-82da-6447acaf8b1b: POST /api/auth/login
[2025-06-12 02:09:15,662] [INFO] app.middleware: Response cf54012b-bf82-4f40-82da-6447acaf8b1b: 400 (0.001s)
[2025-06-12 02:09:26,484] [INFO] app.middleware: Request 9d20f5ec-2e7d-4b8e-a2b1-c46aca0381d4: POST /api/auth/login
[2025-06-12 02:09:26,511] [INFO] app.database: <connection object at 0x0000022F16CF79A0; dsn: 'user=postgres password=xxx dbname=workflow_db host=localhost port=5432', closed: 0>
[2025-06-12 02:09:26,743] [INFO] app.middleware: Response 9d20f5ec-2e7d-4b8e-a2b1-c46aca0381d4: 401 (0.259s)
[2025-06-12 02:09:33,911] [INFO] app.middleware: Request debc6a37-2f0c-47ab-a674-880fe80951af: POST /api/auth/login
[2025-06-12 02:09:33,944] [INFO] app.database: <connection object at 0x0000022F16CF7780; dsn: 'user=postgres password=xxx dbname=workflow_db host=localhost port=5432', closed: 0>
[2025-06-12 02:09:34,160] [INFO] app.middleware: Response debc6a37-2f0c-47ab-a674-880fe80951af: 401 (0.249s)
[2025-06-12 02:12:52,745] [INFO] app: App startup
[2025-06-12 02:13:03,030] [INFO] app.middleware: Request 1e362e51-6812-4bf2-a442-7501cc0142b1: POST /api/auth/login
[2025-06-12 02:13:03,075] [INFO] app.database: Connected to DB postgresql://postgres:CodeSD.com@localhost (connection open: True)
[2025-06-12 02:13:03,261] [INFO] app.middleware: Response 1e362e51-6812-4bf2-a442-7501cc0142b1: 401 (0.231s)
[2025-06-12 02:13:11,604] [INFO] app.middleware: Request c941e42c-bbd5-4e47-9322-d3395ddd1831: POST /api/auth/login
[2025-06-12 02:13:11,636] [INFO] app.database: Connected to DB postgresql://postgres:CodeSD.com@localhost (connection open: True)
[2025-06-12 02:13:11,861] [INFO] app.middleware: Response c941e42c-bbd5-4e47-9322-d3395ddd1831: 401 (0.256s)
[2025-06-12 02:13:16,804] [INFO] app.middleware: Request 785ab131-09c8-4988-81fe-e7ee12b3cda0: POST /api/auth/login
[2025-06-12 02:13:16,935] [INFO] app.database: Connected to DB postgresql://postgres:CodeSD.com@localhost (connection open: True)
[2025-06-12 02:13:17,151] [INFO] app.middleware: Response 785ab131-09c8-4988-81fe-e7ee12b3cda0: 401 (0.347s)
[2025-06-12 02:17:23,549] [INFO] app.middleware: Request 95a0853b-efd5-44c0-a233-8d2b40c24a76: POST /api/auth/login
[2025-06-12 02:17:23,620] [INFO] app.database: Connected to DB postgresql://postgres:CodeSD.com@localhost (connection open: True)
[2025-06-12 02:17:23,840] [INFO] app.middleware: Response 95a0853b-efd5-44c0-a233-8d2b40c24a76: 401 (0.291s)
[2025-06-12 02:17:26,283] [INFO] app.middleware: Request d26e37a6-e5fa-4f9c-9b11-d3c62e54725b: POST /api/auth/login
[2025-06-12 02:17:26,326] [INFO] app.database: Connected to DB postgresql://postgres:CodeSD.com@localhost (connection open: True)
[2025-06-12 02:17:26,543] [INFO] app.middleware: Response d26e37a6-e5fa-4f9c-9b11-d3c62e54725b: 401 (0.260s)
[2025-06-12 02:17:50,146] [INFO] app.middleware: Request dc452e89-c4ee-492b-9b5c-30ca79df13f3: POST /api/auth/login
[2025-06-12 02:17:50,192] [INFO] app.database: Connected to DB postgresql://postgres:CodeSD.com@localhost (connection open: True)
[2025-06-12 02:17:50,432] [INFO] app.middleware: Response dc452e89-c4ee-492b-9b5c-30ca79df13f3: 401 (0.287s)
[2025-06-12 02:18:11,408] [INFO] app.middleware: Request a0b80794-002e-4a08-b655-79ae0068eff6: POST /api/auth/login
[2025-06-12 02:18:11,442] [INFO] app.database: Connected to DB postgresql://postgres:CodeSD.com@localhost (connection open: True)
[2025-06-12 02:18:11,673] [INFO] app.middleware: Response a0b80794-002e-4a08-b655-79ae0068eff6: 401 (0.266s)
[2025-06-12 02:22:17,133] [INFO] app.middleware: Request 83b48f9c-de8e-4888-a74e-13fc550afce4: POST /api/auth/login
[2025-06-12 02:22:17,165] [INFO] app.database: Connected to DB postgresql://postgres:CodeSD.com@localhost (connection open: True)
[2025-06-12 02:22:17,380] [INFO] app.middleware: Response 83b48f9c-de8e-4888-a74e-13fc550afce4: 401 (0.247s)
[2025-06-12 02:25:02,278] [INFO] app.middleware: Request e6f14537-75f7-47c1-babb-a7f16f87d1fb: POST /api/auth/login
[2025-06-12 02:25:02,311] [INFO] app.database: Connected to DB postgresql://postgres:CodeSD.com@localhost (connection open: True)
[2025-06-12 02:25:02,559] [INFO] app.middleware: Response e6f14537-75f7-47c1-babb-a7f16f87d1fb: 401 (0.281s)
[2025-06-12 02:43:13,912] [INFO] app: App startup
[2025-06-12 02:44:56,441] [INFO] app: App startup
[2025-06-12 02:46:19,640] [INFO] app: App startup
[2025-06-12 02:49:15,931] [INFO] app: App startup
[2025-06-12 02:51:11,471] [INFO] app: App startup
[2025-06-12 02:51:54,213] [INFO] app: App startup
[2025-06-12 02:53:49,640] [INFO] app: App startup
[2025-06-12 02:57:08,406] [INFO] app: App startup
[2025-06-12 12:18:28,297] [INFO] app: App startup
[2025-06-12 12:20:39,095] [INFO] app: App startup
[2025-06-12 12:24:20,063] [INFO] app: App startup
[2025-06-12 12:24:21,018] [INFO] app.utils.file_handler: python-magic not available, using alternative MIME detection
[2025-06-12 12:26:10,079] [INFO] app: App startup
[2025-06-12 12:26:10,092] [INFO] app.utils.file_handler: python-magic not available, using alternative MIME detection
[2025-06-12 12:26:10,556] [INFO] app: App startup
[2025-06-12 12:26:10,571] [INFO] app.utils.file_handler: python-magic not available, using alternative MIME detection
[2025-06-12 12:26:16,649] [INFO] app.middleware: Request 52d70b96-fb30-414f-8840-fe6c86b6d6b0: POST /api/auth/login
[2025-06-12 12:26:16,807] [INFO] app.database: Connected to DB postgresql://postgres:CodeSD.com@localhost (connection open: True)
